config/routes.rb
Audioprint::Application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  resources :blog_posts, path: :blog
  match "/blog/:year", :to => "blog_posts#index", via: :get, :constraints => { :year => /\d{4}/ }
  match "/blog/:year/:month", :to => "blog_posts#index", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#show", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#destroy", via: :delete, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug/edit", :to => "blog_posts#edit", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#update", via: :patch, :as => :update, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }

  root :to => "home#index"

  devise_for :users
  resources :users do
    member do
      get :edit_role
      put :change_role
    end
  end
  resources :addresses

  resources :albums, :mix_tapes do
    collection do
      post :sort_tracks
    end

    post :add_songs, :on => :member
  end

  resources :songs do
    member do
      get :ajax_song
    end
  end

  match 'songs/:id/download', :to => 'songs#download', :as => 'download_song', via: :get

  resources :orders do
    member do
      get :checkout
      put :save_address
      post :purchase
      post :review_and_submit

      put :process_order
      patch :ship_order
    end

    collection do
      get :view_cart
    end
  end

  resources :order_items
  resources :charges

  match 'become_contributor', :to => 'users#become_contributor', via: :post
  match 'admin_create', :to => 'users#create', via: :post

  match 'albums/:id/add_to_cart', to: 'order_items#create', as: 'add_album_to_cart', type: 'album', via: :get
  match 'songs/:id/add_to_cart', to: 'order_items#create', as: 'add_song_to_cart', type: 'song', via: :get
end

app/models/mix_tape.rb
class MixTape < Album
  before_create :save_artist

  def save_artist
    self.artist = 'Various Artists'
  end

  def to_s
    self.title
  end
end

app/controllers/mix_tapes_controller.rb
class MixTapesController < ApplicationController
  before_action :set_mix_tape, only: [:show, :edit, :update, :destroy]
  layout "product", only: [:show, :edit, :new]
  load_and_authorize_resource

  def index
    if params[:category]
      @mixtapes = MixTape.without_deleted.where(category_id: params[:category])
    else
      @mixtapes = MixTape.without_deleted
    end

    if params[:search]
      ap, catalog_id = params[:search].upcase.split("AP")

      if catalog_id && is_a_number?(catalog_id)
        @mixtapes = @mixtapes.where(catalog_id: catalog_id)
      else
        @mixtapes = @mixtapes.where("title ILIKE ?", "%#{params[:search]}%")
      end
    end

    @featured_mixtape = MixTape.last
  end

  def show
  end

  def edit
  end

  def new
    @mix_tape = MixTape.new
  end

  def create
    @mix_tape = MixTape.new(params[:mix_tape])
    @mix_tape.user = current_user

    respond_to do |format|
      if @mix_tape.save
        # current_user.add_role :admin, @mix_tape
        format.html { redirect_to edit_mix_tape_path(@mix_tape), notice: 'This album has been created! Now upload some songs! ' }
        format.json { render json: @mix_tape, status: :created, location: @mix_tape }
      else
        format.html { render action: "new" }
        format.json { render json: @mix_tape.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @mix_tape.update_attributes(params[:mix_tape])
        format.html { redirect_to @mix_tape, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mix_tape.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mix_tape.destroy

    respond_to do |format|
      format.html { redirect_to mix_tapes_url }
      format.json { head :no_content }
    end
  end

  def sort_tracks
    if params[:album_id] && params[:song]
      mix_tape = MixTape.find(params[:album_id])

      params[:song].each_with_index do |id, index|
        mix_tape.track_list.update_all({track: index+1}, {id: id})
      end

      respond_to do |format|
        format.json { head :ok }
      end
    else
      respond_to do |format|
        format.json { render :status => :unprocessable_entity }
      end
    end
  end

  def add_songs
    album = MixTape.find(params[:id])
    new_song = album.songs.build(mp3: response.request.request_parameters[:qqfile]) if album

    unless new_song.extract_metadata && new_song.save
      file_name = new_song.mp3.to_s
      new_song.title = File.basename(file_name, File.extname(file_name))
      if new_song.mix_tape.songs.empty?
        new_song.track = 1
      else
        new_song.track = new_song.album.songs.order('track').last.track += 1
      end
    end

    if new_song.save
      render :text => '{"success":true, "id":' + new_song.id.to_s + ', "upload_type":"' + new_song.class.to_s + '"}'
    else
      render :text => '{"error":"failed to upload one or more songs"}'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mix_tape
      @mix_tape = MixTape.without_deleted.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    # def mix_tape_params
    #   params.require(:mix_tape).permit(:title, :catalog_id, :price, :category, :quantity)
    # end
end

app/views/mix_tapes/_form.html.haml
= simple_form_for(@mix_tape, :html => {:multipart => true}) do |f|
  -if @mix_tape.errors.messages[:cover_art]
    .alert.alert-error Upload the Cover Art to finish
  -else
    = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :artist
    = f.input :release_date, :as => :string, :input_html => { :class => 'date_picker' }
    = f.input :category_id, collection: Category.all, include_blank: "Select a Category", label: :Category, label_method: :name, value_method: :id
    = f.input :digital
    = f.input :catalog_id
    = f.input :price
    = f.input :quantity
    Cover Art:
    = f.file_field :cover_art, style: "height: 20px;  line-height: 0px"

  .form-actions{style: "max-width:125px;"}
    = f.button :submit, style: "margin-left:auto;"

app/views/mix_tapes/_mix_tapes_list.html.haml
-unless @albums.empty?
  -for album in @albums
    %li.span3
      .thumbnail.albums
        =link_to album do
          = image_tag album.cover_art.url(:medium)
          %div.titles{style: "margin-top:auto"}
            %h3
              = link_to album.title, album
            %h5
              = link_to album.artist, album
-else
  .empty-album-list
    %h3
      There isn't anything here... 
    %h3
      = link_to 'Go Upload some music!', new_album_path, style: "color: #808080; text-decoration:none;"

app/views/mix_tapes/edit.html.haml
.row
  = simple_form_for(@mix_tape, :html => {:multipart => true}) do |f|
    .large-6.columns.text-centered
      .row
        = image_tag @mix_tape.cover_art.url(:large)
      .row
        .small-12.columns{style: "text-align:left; margin:15px;"}
          %label{style: "text-decoration:underline;"} Upload Cover Art
          = f.file_field :cover_art
    .large-6.columns
      = f.error_notification
      %fieldset
        %legend Album Info
        .row
          .large-6.columns
            = f.input :title
          .large-6.columns
            = f.input :artist
        .row
          .large-6.columns
            = f.input :release_date, :as => :string, :input_html => { :class => 'date_picker' }
          .large-6.columns
            = f.input :digital, collection: {'Physical' => false, 'Digital' => true}, label: :Medium, include_blank: false
          .large-12.columns
            = f.input :category_id, collection: Category.all, include_blank: "Select a Category", label: :Category, label_method: :name, value_method: :id
      %fieldset
        %legend Product Info
        .row
          .large-4.columns
            = f.input :catalog_id
          .large-4.columns
            = f.input :price
          .large-4.columns
            = f.input :quantity unless @mix_tape.digital
      .form-actions
        = f.button :submit, class: 'button', :style => "margin-left: auto; margin-right: auto; width: 100%;"

.row
  .small-12
    %fieldset{style: "margin:0px;padding:10px;"}
      %legend Track Listing
      %table.full-width
        %thead
          %tr
            %th{style: "width:5px;"}
            %th.hide-for-small{style: "width:5px;"} Track
            %th Title
            %th.hide-for-small Length
            - if @mix_tape.digital
              %th.text-centered.hide-for-small{style: "width:65px;"} Size
              %td.text-centered{style: "width:100px;"} Price
            %th{style: "width:10px;"}
        %tbody#tracks{ data: {'update-url' => sort_tracks_mix_tapes_url, 'album-id' => @mix_tape.id} }
          = render partial: "songs/track_edit", collection: @mix_tape.track_list, as: :track
      - if @mix_tape.digital
        .large-6.columns
          %div#bootstrapped-fine-uploader{'data-album-id' => @mix_tape.id}
        .large-6.columns
          %a.button.small-12{href: "/songs/new/?album=#{@mix_tape.id}", "data-reveal-id" => "song-modal", "data-reveal-ajax" => "true", style: "background-color: #1673c1;"} Add Song Manually
      - else
        .large-12.columns
          %a.button.small-12{href: "/songs/new/?album=#{@mix_tape.id}", "data-reveal-id" => "song-modal", "data-reveal-ajax" => "true", style: "background-color: #1673c1;"} Add Song

.reveal-modal#song-modal
  %h3
    Create New Song
  %a#save-song.btn.btn-inverse{href: '#'}
    Save Song
  %a.close-reveal-modal &#215;

app/views/mix_tapes/index.html.haml
.row
  .large-12.columns
    / Navigation
    .row
      .large-12.columns
        %nav.top-bar
          %ul.title-area
            / Title Area
            %li.name
              %h1= link_to 'Mix Tapes', mix_tapes_path
            %li.toggle-topbar.menu-icon
              %a{:href => "#"}
                %span menu
          %section.top-bar-section
            / Right Nav Section
            %ul.right
              %li.divider
              %li.has-dropdown
                %a{:href => "#"} Categories
                %ul.dropdown
                  - Category.all.each do |category|
                    %li
                      = link_to category.name, mix_tapes_path(category: category.id)
                  %li.divider
                  %li
                    = link_to 'View all →', mix_tapes_path
              %li.divider
              / %li.has-dropdown
              /   %a{:href => "#"} Filter By
              /   %ul.dropdown
              /     %li
              /       %a{:href => "#"} Dropdown Option
              /     %li
              /       %a{:href => "#"} Dropdown Option
              /     %li
              /       %a{:href => "#"} Dropdown Option
              /     %li.divider
              /     %li
              /       %a{:href => "#"} See all →
              / %li.divider
              %li.has-form
                = form_tag 'mix_tapes', method: 'get' do
                  .row.collapse
                    .small-10.columns
                      =text_field_tag :search, (params[:search] ? params[:search] : nil), id: 'mix_tapes-search', placeholder: "Search Mix Tapes"
                    .small-2.columns
                      %a.button{:href => "#", onclick: "$(this).closest('form').submit(); return false;"}
                        %i.icon-search
        / End Top Bar
    / End Navigation
    .row
      / Side Bar
      / .large-4.hide-for-small.columns
      /   =link_to @featured_album do
      /     = image_tag @featured_album.cover_art.url(:large)
      /     .panel
      /       %h3= @featured_album.title
      /       %h4= @featured_album.artist
      /       %h5.subheader
      /         This week's featured album is #{@featured_album.title} by #{@featured_album.artist}
      /   %a{:href => "#"}
      /   .panel.callout.radius
      /     %h6
      /       %i.icon-shopping-cart
      /       Add Featured Album to Cart
      / End Side Bar
      / Thumbnails
      .large-12.columns
        .row
          - @mixtapes.each do |album|
            =link_to album do
              .large-2.small-6.columns
                = image_tag album.cover_art.url(:thumb), style: "width:100%;"
                %ul.pricing-table
                  %li.title{style: "font-size:10px;padding:5px;margin:0px;height:20px;line-height:15px;overflow:hidden;"}
                    = truncate album.title, length: 25
                  %li.price{style: "font-size:10px;padding:5px;margin:0px;height:20px;line-height:15px;overflow:hidden;"}
                    = truncate album.artist, length: 25
                    = album.release_date.strftime("%B %d, %Y") if album.release_date


        / End Thumbnails

    / Footer
    %footer.row
      .large-12.columns
        %hr/
        .row
          .large-6.columns
            %p © Copyright Audioprint 2013  .
          / .large-6.columns
          /   %ul.inline-list.right
          /     %li
          /       %a{:href => "#"} Link 1
          /     %li
          /       %a{:href => "#"} Link 2
          /     %li
          /       %a{:href => "#"} Link 3
          /     %li
          /       %a{:href => "#"} Link 4
    / End Footer

app/views/mix_tapes/new.html.haml
%h1 New album

= render 'form'

= link_to 'Back', mix_tapes_path

app/views/mix_tapes/show.html.haml
- cache @mix_tape do
  .row.album-info
    .large-6.columns.text-centered
      = image_tag @mix_tape.cover_art.url(:large)
    .large-6.columns
      %ul.pricing-table
        %li.title
          = "#{@mix_tape.title} - #{@mix_tape.artist}"
          %br
          %small
            = @mix_tape.release_date.strftime("%B %d, %Y") if @mix_tape.release_date
        %li.price
          = number_to_currency(@mix_tape.price, :unit => "$")
        %li.description
          Catalog ID #AP#{@mix_tape.catalog_id}
        %li.bullet-item
          = print_stock(@mix_tape)
        %li.cta-button
          - if @mix_tape.quantity > 0
            = link_to add_album_to_cart_path(@mix_tape), class: 'button' do
              Add to Cart
              %i.fa.fa-shopping-cart
          - else
            %button.disabled
              Out of Stock
              %i.fa.fa-shopping-cart

- cache @mix_tape.track_list do
  .row.track-listings
    .small-12
      %fieldset{style: "margin:5px;padding:5px;"}
        %legend Track Listing
        %table.full-width
          %thead
            %tr
              %th.hide-for-small Track
              %th Title
              %th.hide-for-small Length
              - if @mix_tape.digital
                %th.text-centered

          %tbody#tracks
            = render partial: "songs/track_show", collection: @mix_tape.track_list, as: :track, locals: { digital_track: @mix_tape.digital }

- if can? :manage, @mix_tape
  = link_to 'Edit', edit_mix_tape_path(@mix_tape)
  \|
  = link_to 'Delete', @mix_tape, method: :delete, data: { confirm: 'Are you sure you want to delete this album and all of it\'s songs?' }
  \|
  = link_to 'Back', mix_tapes_path
- else
  = link_to 'Back', mix_tapes_path