config/routes.rb
Audioprint::Application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  resources :blog_posts, path: :blog
  match "/blog/:year", :to => "blog_posts#index", via: :get, :constraints => { :year => /\d{4}/ }
  match "/blog/:year/:month", :to => "blog_posts#index", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#show", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#destroy", via: :delete, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug/edit", :to => "blog_posts#edit", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#update", via: :patch, :as => :update, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }

  root :to => "home#index"

  devise_for :users
  resources :users do
    member do
      get :edit_role
      put :change_role
    end
  end
  resources :addresses

  resources :albums, :mix_tapes do
    collection do
      post :sort_tracks
    end

    post :add_songs, :on => :member
  end

  resources :songs do
    member do
      get :ajax_song
    end
  end

  match 'songs/:id/download', :to => 'songs#download', :as => 'download_song', via: :get

  resources :orders do
    member do
      get :checkout
      put :save_address
      post :purchase
      post :review_and_submit

      put :process_order
      patch :ship_order
    end

    collection do
      get :view_cart
    end
  end

  resources :order_items
  resources :charges

  match 'become_contributor', :to => 'users#become_contributor', via: :post
  match 'admin_create', :to => 'users#create', via: :post

  match 'albums/:id/add_to_cart', to: 'order_items#create', as: 'add_album_to_cart', type: 'album', via: :get
  match 'songs/:id/add_to_cart', to: 'order_items#create', as: 'add_song_to_cart', type: 'song', via: :get
end

app/models/song.rb
class Song < ActiveRecord::Base
  resourcify
  attr_accessible :album_id, :artist, :length, :title, :size, :mp3, :track, :price, :catalog_id
  validates_presence_of :album_id, :title, :length
  belongs_to :album, touch: true
  has_many :order_items
  has_attached_file :mp3, PAPERCLIP_MP3_OPTS

  serialize :metadata
  validates_attachment_size :mp3, :less_than => 20.megabytes
  validates_attachment_content_type :mp3, :content_type => [ 'application/mp3', 'application/x-mp3', 'audio/mpeg', 'audio/mp3' ]

  scope :without_deleted, -> { where(deleted_at: nil) }

  # def audio?
  #   mp3_content_type =~ %r{^audio/(?:mp3|mpeg|mpeg3|mpg|x-mp3|x-mpeg|x-mpeg3|x-mpegaudio|x-mpg)$}
  # end

  def digital
    true
  end

  def to_s
    self.title
  end

  def cover_art(size)
    self.album.cover_art(size)
  end

  def display_catalog_id
    "SNG##{id}"
  end

  def display_length
    Time.at(self.length).utc.strftime("%M:%S") if self.length
  end

  def download_url
    self.mp3.expiring_url(20)
  end

  def downloadable?(user)
    if user.has_role? :admin
      return true
    elsif user.has_role? :admin, self
      return true
    else
      return false
    end
  end

  def extract_metadata
    return unless mp3
    path = mp3.queued_for_write[:original].path
    open_opts = { :encoding => 'utf-8' }
    Mp3Info.open(path, open_opts) do |mp3info|
      self.metadata = mp3info.tag
      self.length = mp3info.length
    end

    if self.metadata
      self.title = self.metadata["title"]
      self.artist = self.metadata["artist"]
      self.track = self.metadata["tracknum"]
      true
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  load_and_authorize_resource

  # SEND_FILE_METHOD = :default
  # GET /songs
  # GET /songs.json
  def index
    unless current_user && current_user.has_role?(:administrator)
      redirect_to '/'
      return
    end

    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])
    render :file => 'public/404.html', :layout => false and return unless @song

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  def new
    redirect_to root_path and return if !params[:album] || request.referer.nil?
    @song = Song.new

    respond_to do |format|
      format.html { render :layout => false }
      format.json { render json: @song }
    end
  end

  def edit
    @song = Song.find(params[:id])
    render :file => 'public/404.html', :layout => false and return unless @song

    if request.referer.nil?
      redirect_to root_path
      return
    elsif URI(request.referer).path != "/albums/#{@song.album.id}/edit"
      redirect_to root_path
      return
    end

    respond_to do |format|
      format.html { render :layout => false }
      format.json { render json: @song }
    end
  end

  def create
    @song = Song.new(params[:song])

    if @song.album
      if @song.album.track_list.empty?
        @song.track ||= 1
      else
        @song.track ||= @song.album.track_list.last.track + 1
      end
    end

    respond_to do |format|
      if @song.save
        format.js { render :template => 'songs/ajax_song' }
        format.html { redirect_to @song.album, notice: 'Song was successfully created.' }
      else
        format.js { render :template => 'songs/ajax_song' }
        format.html { render action: "new" }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])
    render :file => 'public/404.html', :layout => false and return unless @song

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to edit_album_path(@song.album), notice: 'Song was successfully updated.' }
        format.json { head :no_content }
        format.js { render :template => 'songs/update_song', :locals => { :song => @song } }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
        format.js { render :template => 'songs/update_song', :locals => { :song => @song } }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end


  def ajax_song
    @song = Song.find(params[:id])
    return false unless @song
  end


  def download
    render :status => :forbidden, :text => "Nothing here." and return unless song = Song.find_by_id(params[:id])
    render :status => :forbidden, :text => "Forbidden fruit" and return unless song.downloadable?(current_user)

    path = song.mp3.path(params[:style])
    head(:bad_request) and return unless params[:format].to_s == File.extname(path).gsub(/^\.+/, '')

    song.downloads += 1
    if song.save
      redirect_to(song.download_url)
    end
    # send_file_options = { :type => MIME::Types.type_for(path).first.content_type }

    # case SEND_FILE_METHOD
    #   when :apache then send_file_options[:x_sendfile] = true
    #   when :nginx then head(:x_accel_redirect => path.gsub(Rails.root, ''), :content_type => send_file_options[:type]) and return
    # end

    # send_file(path, send_file_options)
  end
end

app/views/songs/_form.html.haml
= simple_form_for(@song, :html => {:multipart => true}, remote: true, authenticity_token: true) do |f|
  %ul.form-errors.alert-box.alert.hidden

  .form-inputs
    = f.input :title
    = f.input :artist
    = f.input :price
    = f.input :length, label: 'Length (in seconds)'
    %label Upload Song
    = f.file_field :mp3, label: 'Upload Song'
  .form-hidden
    = f.input :album_id, as: :hidden, input_html: {value: params[:album].to_i} if params[:album]

  = f.button :submit, class: 'button'

app/views/songs/_track_edit.html.haml
%tr{id: "song-#{track.id}"}
  %td.handle
    %i.fa.fa-sort
  %td.text-centered.hide-for-small
    = track.track
  %td
    = link_to track.title, track
  %td.hide-for-small.hide-for-small
    = Time.at(track.length).strftime("%M:%S") if track.length
  - if (@album && @album.digital) || track.album.digital
    %td.text-centered.hide-for-small
      = number_to_human_size(track.mp3_file_size)
    %td.text-centered
      %span.download-button.full-width{href: '#'}
        %i.fa.fa-shopping-cart
        = number_to_currency(track.price, :unit => "$")
  %td.text-centered
    %a{href: '#', 'data-dropdown' => "settings-#{track.id}"}
      %i.fa.fa-cogs
    %ul.f-dropdown{id: "settings-#{track.id}", 'data-dropdown-content' => ''}
      %li
        %a.edit-song{href: edit_song_path(track)}
          %i.fa.fa-pencil
          Edit Song
      %li
        %a{href: song_path(track), class: 'delete-song', id: "#{track.id}"}
          %i.fa.fa-trash-o
          Delete Song

app/views/songs/_track_show.html.haml
- cache track do
  - if @album.digital
    %tr{id: "song-#{track.id}"}
      %td.hide-for-small
        = track.track
      %td
        = track.title
      %td.hide-for-small
        = track.display_length
      - if @album.digital
        %td.text-centered{style: "width:100px;"}
          - if track.mp3.present? && can?( :manage, Order)
            = link_to add_song_to_cart_path(track), class: 'download-button full-width' do
              %i.fa.fa-shopping-cart
              = number_to_currency(track.price, :unit => "$")

app/views/songs/ajax_song.js.erb
<% if @song.errors.any? %>
  $("ul.form-errors").html('')
  <% @song.errors.full_messages.each do |error| %>
    $("ul.form-errors").append('<li><%= escape_javascript( error ) %></li>');
  <% end %>
  $("ul.form-errors").fadeIn()
<% else %>
  $('form#new_song .alert.alert-box').fadeOut();
  $("ul.form-errors").html('')
  $('form#new_song').prepend('<div class="alert-box success" data-alert style="display:none;">Successfully Added Song<a class="close" href="#">x</div>');
  $('form#new_song .success.alert-box').fadeIn();
  $('form#new_song .form-inputs input').val('');

  var new_song = "<%= escape_javascript( render(:partial => 'songs/track_edit', :locals => {track: @song}) ) %>"
  $("tbody#tracks").append(new_song);
  $('.qq-upload-success').fadeOut();
<% end %>

app/views/songs/edit.html.haml
%h3.subheader Editing #{@song.title}

= render 'form'

%a.close-reveal-modal &#215;

app/views/songs/index.html.haml
%h1 Listing songs

%table
  %tr
    %th Title
    %th Artist
    / %th Length
    / %th Size
    %th Album
    %th
    %th
    %th

  - @songs.each do |song|
    %tr
      %td= song.title
      %td= song.artist
      / %td= song.length
      / %td= song.size
      %td= song.album.title
      -if can? :edit, song
        %td= link_to 'Show', song
        %td= link_to 'Edit', edit_song_path(song)
        %td= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' }

%br
-if can? :create, Song
  = link_to 'New Song', new_song_path

app/views/songs/new.html.haml
%h3.subheader Create New Song

= render 'form'

%a.close-reveal-modal &#215;

app/views/songs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @song.title
%p
  %b Artist:
  = @song.artist
%p
  %b Length:
  = Time.at(@song.length).utc.strftime("%M:%S") if @song.length
%p
  %b Downloads:
  = @song.downloads
%p
  %b Album:
  = @song.album.title

= link_to 'Edit', edit_song_path(@song)
\|
= link_to 'Back', request.env["HTTP_REFERER"] || @song.album

app/views/songs/update_song.js.erb
<% if @song.errors.any? %>
  $("ul.form-errors").html('')
  <% @song.errors.full_messages.each do |error| %>
    $("ul.form-errors").append('<li><%= escape_javascript( error ) %></li>');
  <% end %>
  $("ul.form-errors").fadeIn()
<% else %>
  $('form.edit_song .alert.alert-box').fadeOut();
  $("ul.form-errors").html('')
  $('form.edit_song').prepend('<div class="alert-box success" data-alert style="display:none;">Successfully Updated Song<a class="close" href="#">x</div>');
  $('form.edit_song .success.alert-box').fadeIn();

  var updated_song = "<%= escape_javascript( render(:partial => 'songs/track_edit', :locals => {track: song}) ) %>"
  $("tbody#tracks tr#song-<%=@song.id%>").replaceWith(updated_song);
<% end %>