config/routes.rb
Audioprint::Application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  resources :blog_posts, path: :blog
  match "/blog/:year", :to => "blog_posts#index", via: :get, :constraints => { :year => /\d{4}/ }
  match "/blog/:year/:month", :to => "blog_posts#index", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#show", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#destroy", via: :delete, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug/edit", :to => "blog_posts#edit", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#update", via: :patch, :as => :update, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }

  root :to => "home#index"

  devise_for :users
  resources :users do
    member do
      get :edit_role
      put :change_role
    end
  end
  resources :addresses

  resources :albums, :mix_tapes do
    collection do
      post :sort_tracks
    end

    post :add_songs, :on => :member
  end

  resources :songs do
    member do
      get :ajax_song
    end
  end

  match 'songs/:id/download', :to => 'songs#download', :as => 'download_song', via: :get

  resources :orders do
    member do
      get :checkout
      put :save_address
      post :purchase
      post :review_and_submit

      put :process_order
      patch :ship_order
    end

    collection do
      get :view_cart
    end
  end

  resources :order_items
  resources :charges

  match 'become_contributor', :to => 'users#become_contributor', via: :post
  match 'admin_create', :to => 'users#create', via: :post

  match 'albums/:id/add_to_cart', to: 'order_items#create', as: 'add_album_to_cart', type: 'album', via: :get
  match 'songs/:id/add_to_cart', to: 'order_items#create', as: 'add_song_to_cart', type: 'song', via: :get
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :status, :user, :address_id, :shipping_confirmation
  belongs_to :user, foreign_key: :user_id
  belongs_to :address
  has_many :order_items, dependent: :destroy

  def self.status_types
    @@status_types ||= ["Unsubmitted", "Confirmed", "Processed", "Shipped"]
  end

  def is_valid?
    address.present?
  end

  def shipping_cost
    0
  end

  def sales_tax
    0
  end

  def subtotal
    self.order_items.collect(&:subtotal).sum
  end

  def total
    self.order_items.collect(&:subtotal).sum + shipping_cost + sales_tax
  end

  def confirm(customer, options={})
    if options[:stripe_card_token]
      self.update_column(:status, "Confirmed") if Stripe::Charge.create(
        :amount => (total * 100).to_i,
        :currency => "usd",
        :card => options[:stripe_card_token],
        :metadata => {
          order_id: id,
          customer_id: customer.id,
          customer_name: customer.name,
          shipping_address: address.to_s
        }
      )
    end

    if status == "Confirmed"
      OrderMailer.confirm_order(customer, self).deliver
      return true
    else
      return false
    end
  end

  def process
    return false unless self.status == "Confirmed"
    if self.update_column(:status, "Processed")
      self.order_items.each do |item|
        unless item.product.digital
          item.product.update_column(:quantity, item.product.quantity - item.quantity)
        end
        # backorder = 0 - product.quantity if product.quantity < 0
      end
      OrderMailer.process_order(user, self).deliver
      return true
    else
      return false
    end
  end


  def ship
    return false unless status == "Processed"
    if self.update_column(:status, "Shipped")
      OrderMailer.ship_order(user, self).deliver
      return true
    else
      return false
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource

  def view_cart
    load_order

    respond_to do |format|
      format.html { redirect_to @order }
      format.json { render json: @order }
    end
  end

  def checkout
    authenticate_user!
    @order = Order.find(params[:id])
    render :file => 'public/404.html', :layout => false and return unless @order
    sign_out current_user unless can? :manage, @order

    @address = Address.where(user_id: current_user.id).order(updated_at: :desc).last
    @address ||= Address.new()

    if @order.order_items.empty?
      @order.errors.add(:error, ": You don't have any items in your cart")
    end

    if @order.status != 'Unsubmitted'
      @order.errors.add(:error, ": This order can not be processed")
    end

    if @order.errors.any?
      render action: "show"
    end
  end


  def save_address
    authenticate_user!

    @order = Order.find(params[:id])
    sign_out current_user unless can? :manage, @order

    @address = Address.find_by_id(params[:preloaded_address]) if params[:preloaded_address].present?
    @address ||= Address.new(params[:address])
    @address.user_id = current_user.id if params[:save_it]

    @order.address = @address

    if @order.save && @address.save
      render json: {order: @order, address: @address}, status: :created
    else
      render json: {order: @order.errors, address: @address.errors}, status: :unprocessable_entity
    end
  end

  def review_and_submit
    authenticate_user!

    @order = Order.find(params[:id])
    sign_out current_user unless can? :manage, @order

    if @order.is_valid? && @order.confirm(current_user, { stripe_card_token: params[:stripe_card_token] })
      redirect_to @order
    else
      render action: "checkout"
    end
  end


  def process_order
    authorize_admin

    @order = Order.find(params[:id])

    if @order.process
      redirect_to orders_path, notice: 'This order has been processed.'
    else
      redirect_to orders_path, alert: 'There was an error processing this order.'
    end
  end

  def ship_order
    authorize_admin

    @order = Order.find(params[:id])

    unless @order.status == "Processed" || @order.status == "Shipped"
      redirect_to @order, alert: "This order cannot be processed"
    end

    @order.update_attributes(params[:order])

    if @order.status == "Shipped"
      redirect_to orders_path, notice: "This order's confirmation # has been updated."
    elsif @order.ship
      redirect_to orders_path, notice: 'This order has now been shipped!'
    else
      redirect_to orders_path, alert: 'There was an error with this order.'
    end
  end


  def index
    authenticate_user!

    if current_user.has_role? :admin
      @orders = Order.all
      render :template => "orders/manage"
    else
      @orders = Order.where(user_id: current_user.id)
    end
  end


  def show
    @order = Order.find(params[:id])
    render :file => 'public/404.html', :layout => false and return unless @order

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  def edit
    @order = Order.find(params[:id])
    render :file => 'public/404.html', :layout => false and return unless @order
  end

  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @order = Order.find(params[:id])
    render :file => 'public/404.html', :layout => false and return unless @order

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_checkout_billing.html.haml
= form_tag purchase_order_path(@order), id: "billing-form", class: '' do
  %div#stripe_error.form-errors.alert-box.alert.hidden
  .field
    = label_tag :card_number, "Credit Card Number "
    = text_field_tag :card_number, nil, name: nil
  .field
    = label_tag :card_code, "Security Code on Card (CVV)"
    = text_field_tag :card_code, nil, name: nil
  .field
    = label_tag :card_month, "Card Expiration"
    = select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month"}
    = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"}
  .field
    = submit_tag 'Submit Payment', class: 'button right'

app/views/orders/_checkout_order_item.html.haml
%tr.cart-row
  %td.item-image.hide-for-small
    = image_tag item.product.cover_art(:thumb)
  %td.item-details
    .name
      = link_to item.product, item.product
    %br
    .stock
      %span.title
        Stock:
      %span
        = print_stock(item.product, item.quantity)
    .attribute
      %span.title
        Price:
      %span
        = number_to_currency(item.product.price)
    .sku
      %span.title
        Item:
      %span
        = item.product.display_catalog_id
  %td.item-quantity-details
    / .editdetails
    /   Edit Item
    %span.item-quantity
      = "#{item.quantity}x"
  %td.item-total
    %span Subtotal:
    %span.title
      = number_to_currency(item.subtotal)

app/views/orders/_checkout_review.html.haml
= form_tag review_and_submit_order_path(@order), id: "review-form" do
  %div#stripe_error.form-errors.alert-box.alert.hidden
  = hidden_field_tag :stripe_card_token
  .small-12.small-centered.columns
    %table#review-cart-items
      %tbody
        = render partial: 'checkout_order_item', collection: @order.order_items, as: :item
  .small-12.small-centered.columns
    %table#review-cart-total
      %tbody
        %tr.order-subtotal
          %td Subtotal:
          %td= number_to_currency(@order.subtotal, :unit => "$")
        %tr.order-shipping
          %td Shipping:
          %td= number_to_currency(@order.shipping_cost, :unit => "$")
        %tr.order-sales-tax
          %td Sales Tax:
          %td= number_to_currency(@order.sales_tax, :unit => "$")
        %tr.order-total
          %td Order Total
          %td= number_to_currency(@order.total, :unit => "$")
    #submit-order.right
      = submit_tag 'Submit Order', class: 'button'

app/views/orders/_form.html.haml
= simple_form_for @order, url: '/' do |f|
  - if @order.errors.any?
    - @order.errors.full_messages.each do |msg|
      .alert-box.alert{"data-alert" => ""}
        %a.close{href:'#'}x
        = msg

  %h1 Your Order
  %table.full-width
    %tr
      %th Customer
      %td{colspan: 6}=  @order.user ? @order.user.name : "Not Logged In"
    %tr
      %th Status:
      %td{colspan: 6}= @order.status
    %tr
      %th Items:
      %td{colspan: 6}= @order.order_items.count
    %tr
      %th Items
      %th Title
      %th Quantity
      %th Stock
      %th Unit Price
      %th Subtotal

    = render partial: 'order_item', collection: @order.order_items

    %tr.text-centered
      %th{colspan: 4}
      %th Order Total
      %th#order-total= number_to_currency(@order.total)

  %div{style: "overflow:hidden;"}
    .small-12
      .right
        #continue.button Continue Shopping
        %a#checkout.button{ href: checkout_order_path(@order) } Checkout

app/views/orders/_order_item.html.haml
- if order_item.product_type == 'Album'
  %tr.text-centered{id: "item-#{order_item.id}"}
    %td
      = link_to order_item.product do
        = image_tag order_item.product.cover_art(:thumb)
        %span{style: "display:block; padding: 5px; font-size:14px;" }= order_item.product.title
        %span{style: "color: gray; font-size:10px;"} (album)
    %td
      = link_to order_item.product
    %td
      %div.quantity
        = order_item.quantity
      %br
      %div
        = link_to '+', order_item_path(order_item), class: 'button tiny success add-quantity'
        = link_to '-', order_item_path(order_item), class: 'button tiny alert subtract-quantity'
      %div
        = link_to order_item, class: 'delete-item button alert tiny' do
          Remove
    %td.stock
      = print_stock(order_item.product, order_item.quantity)
    %td.unit-price
      = number_to_currency(order_item.product.price)
    %td.subtotal
      = number_to_currency(order_item.subtotal)
- else
  %tr.text-centered{id: "item-#{order_item.id}"}
    %td
      = link_to order_item.product.album do
        = image_tag order_item.product.cover_art(:thumb)
        %span{style: "display:block; padding: 5px; font-size:14px;" }= order_item.product.title
        %span{style: "color: gray; font-size:10px;"} (song)
    %td
      = link_to order_item.product
    %td
      %div.quantity
        = order_item.quantity
      %br
      %div
        = link_to '+', order_item_path(order_item), class: 'button tiny success add-quantity'
        = link_to '-', order_item_path(order_item), class: 'button tiny alert subtract-quantity'
      %div
        = link_to order_item, class: 'delete-item button alert tiny' do
          Remove
    %td.stock
      Digital
    %td.unit-price
      = number_to_currency(order_item.product.price)
    %td.subtotal
      = number_to_currency(order_item.subtotal)

app/views/orders/address.html.haml
/ = simple_form_for @order, url:  do |f|
/   - if @order.errors.any?
/     - @order.errors.full_messages.each do |msg|
/       .alert-box.alert{"data-alert" => ""}
/         %a.close{href:'#'}x
/         = msg

/ %h1 Your Order
/ %table.full-width
/   %tr
/     %th Customer
/     %td{colspan: 6}=  @order.user ? @order.user.name : "Not Logged In"
/   %tr
/     %th Status:
/     %td{colspan: 6}= @order.status
/   %tr
/     %th Items:
/     %td{colspan: 6}= @order.order_items.count
/   %tr
/     %th Items
/     %th Title
/     %th Quantity
/     %th Stock
/     %th Unit Price
/     %th Subtotal

/   = render partial: 'item', collection: @order.order_items

/   %tr.text-centered
/     %th{colspan: 4}
/     %th Order Total
/     %th#order-total= number_to_currency(@order.total)

= render partial: 'addresses/form'
/ .small-10.large-6.columns
/   .div Shipping To:
/   .address
/     = f.association :address, collection: current_user.addresses, selected: current_user.addresses.any? ? current_user.addresses.last.id : nil, include_blank: 'No Address on File', label: false
/     = link_to 'Add new address', new_address_path, 'data-reveal-id' => 'address-modal', 'data-reveal-ajax' => 'true'

/ %div{style: "overflow:hidden;"}
/   .small-12
/     .right
/       #continue.button Cancel
/       %a{ href: payment_order_path(@order) }#checkout.button Continue Checkout

app/views/orders/checkout.html.haml
= content_for :head do
  = tag :meta, :name => "stripe-key", :content => Rails.configuration.stripe[:publishable_key]

#shipping.checkout-section.on
  %h2
    %span.label 1
    Shipping Address
  %hr
  .edit
    .button.secondary Edit
  .form-data
    = render partial: 'addresses/form'
  .info-data

#billing.checkout-section.off
  %h2
    %span.label 2
    Billing
  %hr
  .edit{style: 'display:none;'}
    .button.secondary Edit
  .form-data
    = render partial: 'checkout_billing'
  .info-data
#review.checkout-section.off
  %h2
    %span.label 3
    Review & Submit
  .form-data
    = render partial: 'checkout_review'
  .info-data

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Listing orders

%table.full-width
  %tr.text-centered
    %th Order ID
    %th User
    %th Status
    %th Total

  - @orders.each do |order|
    %tr.text-centered
      %td= link_to order.id, order
      %td= link_to order.user.name, order.user if order.user
      %td= order.status
      %td= number_to_currency(order.total)
      - if order.status == "Unsubmitted"
        %td
          = link_to order, class: 'button alert tiny', :method => :delete, :data => { :confirm => 'Are you sure?' } do
            %i.icon-remove
            Remove
.row.collapse
  .right
    Total of all orders:
    =number_to_currency(current_user.orders.collect(&:total).sum)


%br

app/views/orders/manage.html.haml
%h1 All orders

%table.full-width
  %tr.text-centered
    %th Order ID
    %th User
    %th Status
    %th Total

  - @orders.each do |order|
    %tr.text-centered
      %td= link_to order.id, order
      %td= link_to order.user.name, order.user if order.user
      %td= order.status
      %td= number_to_currency(order.total)
      - if order.status == "Unsubmitted"
        %td
          = link_to order, class: 'button alert medium', :method => :delete, :data => { :confirm => 'Are you sure?' } do
            %i.icon-remove
            Remove Order
      - if order.status == "Confirmed"
        %td
          = link_to process_order_order_path(order), method: :put, class: 'button medium', :data => { :confirm => 'Are you sure?' } do
            %i.icon-plus
            Process Order
      - if order.status == "Processed"
        %td
          .ship-order.success.button.medium Ship Order
          = simple_form_for order, url: ship_order_order_path(order), :html => {:multipart => true, :class => 'confirmation-form small-6'} do |f|
            = f.input :shipping_confirmation, label: false
            = f.button :submit, 'Save Confirmation', class: 'button', :data => { :confirm => 'Are you sure you want to submit?  This will notify the customer.' }
          .cancel-ship.button.alert{style: "display:none;"} Cancel
      - if order.status == "Shipped"
        %td
          .ship-order.success.button.medium Edit Confirmation
          = simple_form_for order, url: ship_order_order_path(order), :html => {:multipart => true, :class => 'confirmation-form small-6'} do |f|
            = f.input :shipping_confirmation, label: false
            = f.button :submit, 'Save Confirmation', class: 'button', :data => { :confirm => 'Are you sure you want to save a new confirmation # ?' }
          .cancel-ship.button.alert{style: "display:none;"} Cancel
.row.collapse
  .right
    Total of all orders:
    =number_to_currency(current_user.orders.collect(&:total).sum)


%br

app/views/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p#notice= notice

- if @order.status == 'Unsubmitted'
  = render partial: 'form'

- elsif @order.status == "Confirmed" || @order.status == "Processed"
  %h1 Order ##{@order.id}
  %table.full-width
    %tr
      %th Customer
      %td{colspan: 7}=  @order.user ? @order.user.name : "Not Logged In"
    %tr
      %th Status:
      %td{colspan: 7}= @order.status
    %tr
      %th Address:
      %td= @order.address.to_s
    %tr
      %th Items:
      %td{colspan: 7}= @order.order_items.count
    %tr
      %th.hide-for-small Items
      %th Title
      %th Quantity
      %th Stock
      %th Unit Price
      %th Subtotal
    - @order.order_items.each do |item|
      %tr{id: "item-#{item.id}"}
        %td.hide-for-small= image_tag item.product.cover_art(:thumb)
        %td= link_to item.product, item.product_type == 'Album' ? item.product : item.product.album
        %td= item.quantity
        %td= print_stock(item.product, item.quantity)
        %td= number_to_currency(item.product.price)
        %td= number_to_currency(item.subtotal)

  .row.collapse
    .right.label
      %h3 Order Total
      %strong{style: "font-size:14px;"}= number_to_currency(@order.total)

  / %br
  / .row.collapse
  /   %a.button.right.alert.disabled{href:'#'}Cancel Order