config/routes.rb
Audioprint::Application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  resources :blog_posts, path: :blog
  match "/blog/:year", :to => "blog_posts#index", via: :get, :constraints => { :year => /\d{4}/ }
  match "/blog/:year/:month", :to => "blog_posts#index", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#show", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#destroy", via: :delete, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug/edit", :to => "blog_posts#edit", via: :get, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }
  match "/blog/:year/:month/:slug", :to => "blog_posts#update", via: :patch, :as => :update, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :slug => /[a-z0-9\-]+/ }

  root :to => "home#index"

  devise_for :users
  resources :users do
    member do
      get :edit_role
      put :change_role
    end
  end
  resources :addresses

  resources :albums, :mix_tapes do
    collection do
      post :sort_tracks
    end

    post :add_songs, :on => :member
  end

  resources :songs do
    member do
      get :ajax_song
    end
  end

  match 'songs/:id/download', :to => 'songs#download', :as => 'download_song', via: :get

  resources :orders do
    member do
      get :checkout
      put :save_address
      post :purchase
      post :review_and_submit

      put :process_order
      patch :ship_order
    end

    collection do
      get :view_cart
    end
  end

  resources :order_items
  resources :charges

  match 'become_contributor', :to => 'users#become_contributor', via: :post
  match 'admin_create', :to => 'users#create', via: :post

  match 'albums/:id/add_to_cart', to: 'order_items#create', as: 'add_album_to_cart', type: 'album', via: :get
  match 'songs/:id/add_to_cart', to: 'order_items#create', as: 'add_song_to_cart', type: 'song', via: :get
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert-box{:class => "#{name == :notice ? "success" : "error"}", "data-alert" => ""}
      %a.close{href: '#'} x
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        %a#brand{href: root_path }
          = image_tag('audio_logo.png')
    %li.toggle-topbar.menu-icon
      %a{href:'#'}
        %span Menu

  %section.top-bar-section
    %ul.left
      %li.divider
      %li{class: "#{params[:controller] == 'blog_posts' ? 'active' : ''}"}
        = link_to 'Home', blog_posts_path
      %li.divider
      %li{class: "#{params[:controller] == 'albums' ? 'active' : ''}"}
        = link_to 'Albums', albums_path
        %li.divider
      - if current_user && (can? :read, MixTape)
        %li{class: "#{params[:controller] == 'mix_tapes' ? 'active' : ''}"}
          = link_to 'Mix Tapes', mix_tapes_path
          %li.divider
      - if current_user && current_user.has_role?(:admin)
        %li.has-dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Create
            %b.caret
          %ul.dropdown
            %li
              = link_to 'Album', new_album_path
            %li
              = link_to 'Blog', new_blog_post_path
            %li
              = link_to 'User', new_user_path
            %li
              = link_to 'MixTape', new_mix_tape_path
        %li.divider
    %ul.right
      - if can? :manage, Order
        %li.divider
        %li
          = link_to view_cart_orders_path do
            View Cart
            %i.icon-shopping-cart
      %li.divider
      - if user_signed_in?
        %li.has-dropdown.userdrop
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            = current_user.name
            = image_tag avatar_url(current_user), width: 40, height: 40
          %ul.dropdown
            - if current_user.has_role? :admin
              / %li
              /   = link_to '#' do
              /     %i.icon-th-large
              /     Edit Front Page
              %li
                = link_to users_path do
                  %i.icon-dashboard
                  Administration
            %li
              = link_to orders_path do
                %i.icon-list-alt
                Manage Orders
            %li
              = link_to edit_user_registration_path do
                %i.icon-edit
                Account Info
            %li.divider
            %li
              = link_to destroy_user_session_path, :method=>'delete' do
                %i.icon-road
                Sign Out
      -else
        %li{style: "margin-top: 10px; font-size: 15px;"}
        %li.divider
        %li
          = link_to 'Sign Up', new_user_registration_path
        %li{style: "margin-top: 10px; font-size: 15px;"}
        %li.divider
        %li
          = link_to 'Login', new_user_session_path
        %li{style: "margin-top: 10px; font-size: 15px;"}
        %li.divider

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }
  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  %link{href: 'http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic', rel:'stylesheet', type:'text/css'}
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
  %meta{:content => content_for?(:description) ? yield(:description) : "Audioprint()", :name => "description"}
  %title= content_for?(:title) ? yield(:title) : "Audioprint()"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery?
  = javascript_include_tag "application", "https://js.stripe.com/v2/"

  = csrf_meta_tag
  = yield(:head)

%body{:class => "#{controller_name} #{action_name}"}
  = render 'layouts/navigation'
  .row
    .small-12.large-6.small-centered.columns
      = render 'layouts/messages'
  .row
    .content.small-12.large-10.small-centered.columns
      = yield

:plain
  </html>

app/views/layouts/landing.html.haml
!!!
%html
  %head
    =javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery?
    %link{href: 'http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic', rel:'stylesheet', type:'text/css'}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Audioprint()"
    %meta{:content => content_for?(:description) ? yield(:description) : "Audioprint()", :name => "description"}
      = stylesheet_link_tag "application", :media => "all"
      = javascript_include_tag "application", "https://js.stripe.com/v2/"
      = csrf_meta_tags
      = yield(:head)
  %body.login-container{:class => "#{controller_name} #{action_name}"}
    / = render 'layouts/navigation'
    / = render 'layouts/messages'
    = yield
    / %header.navbar.navbar-fixed-top.navbar-inverse{style: "position:fixed;"}
    /   %nav.navbar-inner
    /     .container{style: "margin-left: 20px;"}
    /       = render 'layouts/navigation'
    .welcome
      .visible-phone
        %h1 Welcome to the future of Music Distribution
        %h2 Sign up and see how you can reach new customers!
        = link_to new_user_registration_path do
          .btn.btn-inverse.btn-large
            Create An Account Today!
      .hidden-phone
        %h1 Welcome to the future
        %h1 of Music Distribution
        %h2 Sign up and see how you can reach new customers!
        = link_to new_user_registration_path do
          .btn.btn-inverse.btn-large
            Create An Account Today!

app/views/layouts/product.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }
  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  %link{href: 'http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic', rel:'stylesheet', type:'text/css'}
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
  %meta{:content => content_for?(:description) ? yield(:description) : "Audioprint()", :name => "description"}
  %title= content_for?(:title) ? yield(:title) : "Audioprint()"

  = stylesheet_link_tag "application"
  = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery?
  = javascript_include_tag "application", "https://js.stripe.com/v2/", "vendor/custom.modernizr"
  = csrf_meta_tag
  = yield(:head)

%body{:class => "#{controller_name} #{action_name}"}
  = render 'layouts/navigation'
  .row
    .small-10.small-centered.columns
      = render 'layouts/messages'
  .row
    .content.small-10.small-centered.columns
      = yield

:plain
  </html>

app/views/layouts/product_show.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }
  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  %link{href: 'http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic', rel:'stylesheet', type:'text/css'}
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
  %meta{:content => content_for?(:description) ? yield(:description) : "Audioprint()", :name => "description"}
  %title= content_for?(:title) ? yield(:title) : "Audioprint()"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery?
  = csrf_meta_tag
  = yield(:head)

%body{:class => "#{controller_name} #{action_name}"}
  = render 'layouts/navigation'
  / = render 'layouts/messages'
  .row
    .content.small-10.small-centered.columns
      = yield